version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Specify the Node.js version
    commands:
      - echo Installing dependencies...
      - npm install # Install project dependencies
  build:
    commands:
      - echo Building the React application...
      - npm run build # Build the React app
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app)

cache:
  paths:
    - node_modules/** # Cache dependencies to speed up subsequent builds